# Generated by Django 5.0.1 on 2024-01-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webchat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="Conversation",
            new_name="conversation",
        ),
    ]
