# Generated by Django 5.0.1 on 2024-01-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catoegory",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="server",
            old_name="catoegory",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
