# Generated by Django 5.0.1 on 2024-01-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_category",
                to="server.category",
            ),
        ),
    ]
